pythonpath = ["src",]

[tool.mypy]
namespace_packages = true
explicit_package_bases = true
strict = true
mypy_path = "src:."
follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
check_untyped_defs = true
no_implicit_reexport = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "PTH", "G", "T10", "A", "PL", "RUF100", "PGH004", "N", "ANN", "EXE"]
ignore = [
  "PLR0912", "PLR0915", "PLR2004", "PLR0913", "PLR1714", "PLR0911", # Over-opinionated
  "G004", # F-string in logging
  "UP028", # Use yield from
  "UP007", # "Use | instead of union
  "ANN002", "ANN003", "ANN101", "ANN102", "ANN201", "ANN202", "ANN204", "ANN401", # Type hints needed
  "I001", # No need as using formatter
  "PTH123", # Do not recommend using Path.open()

]